# 构建时把 SKILL.md 嵌入为 C++ raw string 头文件（供 CLI --prompt 输出）
#
# 用法（由 CMakeLists.txt add_custom_command 调用）：
#   cmake -DSKILL_FILE=... -DOUT_FILE=... -P embed_skill.cmake
#
# 生成内容：
#   #pragma once
#   namespace sps { constexpr const char* kSkillPrompt = R"skill_prompt(...)skill_prompt"; }

if(NOT DEFINED SKILL_FILE OR NOT DEFINED OUT_FILE)
  message(FATAL_ERROR "embed_skill.cmake: SKILL_FILE and OUT_FILE are required")
endif()

file(READ "${SKILL_FILE}" content)

# raw string 定界符防护：内容中出现 ")skill_prompt" 会提前终止字符串。
# 这里用逐段替换把所有 ")skill_prompt" 转义为 "\)skill_prompt"（内容中几乎不可能出现，
# 仅作防御；C++ raw string 中反斜杠不转义，该序列原样输出无碍）。
string(REPLACE ")skill_prompt\"" ")skill_prompt\\\"" content "${content}")

set(hdr
"// auto-generated by embed_skill.cmake from ${SKILL_FILE}
// Do not edit manually.
#pragma once

namespace sps {
constexpr const char* kSkillPrompt = R\"skill_prompt(${content})skill_prompt\";
}
")

file(WRITE "${OUT_FILE}" "${hdr}")
message(STATUS "embed_skill: wrote ${OUT_FILE} (${content} bytes)")
